spring:
  thymeleaf:
    prefix: classpath:/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    check-template-location: true
    suffix: .html   # 파일 확장자
    cache: false
    mvc:
      static-path-pattern: /static/** # spring mvc 정적경로 변경