name: CI

on:
  push:
    branches: ["main", "release", "staging", "develop"]
  pull_request:
    branches: ["main", "release", "staging", "develop"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
#      - name: Lint
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#        with:
#          arguments: checkFormat # TODO: 왜 안되는지 알아보기..
      - name: Add permission
        run: chmod +x gradlew

      - name: Test
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test
